env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
settings: {}
rules: {
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extension: 0
}
